"use client"

// pages/privacy-policy.tsx
import React from 'react';
import Head from 'next/head';
import { Button } from '../components/ui/button';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

const PrivacyPolicy: React.FC = () => {
  return (
    <>
     
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-6">
            <Link href="/" passHref>
              <Button variant="ghost" className="mb-4">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>

            <h1 className="text-3xl font-bold text-gray-900">Privacy Policy</h1>
            <p className="text-gray-600 mt-2">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="bg-white rounded-lg shadow-sm p-8 space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Information We Collect</h2>
              <p className="text-gray-700 mb-4">
                FakerBox is a client-side application that generates fake data for development and testing purposes. We collect minimal information to provide and improve our services:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li><strong>Usage Analytics:</strong> We use Google Analytics to understand how users interact with our service, including page views, session duration, and feature usage.</li>
                <li><strong>Device Information:</strong> Basic device and browser information for optimizing user experience.</li>
                <li><strong>Cookies:</strong> We use cookies for analytics and advertising purposes (see Cookie Policy below).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">2. How We Use Information</h2>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>To provide and maintain our fake data generation service</li>
                <li>To analyze usage patterns and improve user experience</li>
                <li>To display relevant advertisements through Google AdSense</li>
                <li>To ensure the security and proper functioning of our service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Data Storage and Security</h2>
              <p className="text-gray-700 mb-4">
                All fake data generated by FakerBox is created locally in your browser and is not stored on our servers. We implement appropriate security measures to protect any information we do collect.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Third-Party Services</h2>
              <p className="text-gray-700 mb-4">We use third-party services that may collect information:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li><strong>Google Analytics:</strong> For website analytics and user behavior tracking</li>
                <li><strong>Google AdSense:</strong> For displaying advertisements</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Cookies Policy</h2>
              <p className="text-gray-700 mb-4">
                We use cookies and similar tracking technologies to enhance your experience:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li><strong>Essential Cookies:</strong> Required for basic site functionality</li>
                <li><strong>Analytics Cookies:</strong> Help us understand how users interact with our site</li>
                <li><strong>Advertising Cookies:</strong> Used to display relevant ads and measure ad performance</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Your Rights</h2>
              <p className="text-gray-700 mb-4">You have the right to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Opt-out of analytics tracking</li>
                <li>Disable cookies in your browser settings</li>
                <li>Request information about data we collect</li>
                <li>Request deletion of your data</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Contact Us</h2>
              <p className="text-gray-700">
                If you have any questions about this Privacy Policy, please contact us at{' '}
                <a href="mailto:privacy@fakerbox.com" className="text-blue-600 hover:underline">
                  privacy@fakerbox.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
