"use client"

// pages/terms-of-service.tsx
import React from 'react';
import Head from 'next/head';
import { Button } from '../components/ui/button';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

const TermsOfService: React.FC = () => {
  return (
    <>
     

      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-6">
            <Link href="/" passHref>
              <Button variant="ghost" className="mb-4">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>

            <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
            <p className="text-gray-600 mt-2">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="bg-white rounded-lg shadow-sm p-8 space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700">
                By accessing and using FakerBox, you accept and agree to be bound by the terms and provision of this agreement. 
                If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Service Description</h2>
              <p className="text-gray-700 mb-4">
                FakerBox is a free web-based tool that generates fake data for development, testing, and educational purposes. 
                The service includes various data generators for names, addresses, emails, and other common data types.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Acceptable Use</h2>
              <p className="text-gray-700 mb-4">You agree to use FakerBox only for lawful purposes and in accordance with these Terms. You agree NOT to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Use the generated data to impersonate real individuals</li>
                <li>Use the service for any fraudulent, illegal, or harmful activities</li>
                <li>Attempt to overwhelm our servers with excessive requests</li>
                <li>Reverse engineer, modify, or create derivative works of the service</li>
                <li>Use the service to spam, harass, or harm others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Generated Data Disclaimer</h2>
              <p className="text-gray-700 mb-4">
                All data generated by FakerBox is entirely fictional and created using algorithms. Any resemblance to real persons, 
                living or dead, or actual places, events, or businesses is purely coincidental. Users are responsible for ensuring 
                appropriate use of generated data.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Service Availability</h2>
              <p className="text-gray-700">
                We strive to keep FakerBox available 24/7, but we do not guarantee uninterrupted service. We may temporarily 
                suspend the service for maintenance, updates, or other operational reasons.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Intellectual Property</h2>
              <p className="text-gray-700">
                The FakerBox service, including its design, functionality, and underlying code, is protected by intellectual 
                property laws. Generated data is not subject to copyright and may be used freely for legitimate purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Limitation of Liability</h2>
              <p className="text-gray-700">
                FakerBox is provided "as is" without warranties of any kind. We shall not be liable for any damages arising 
                from the use or inability to use this service, including but not limited to direct, indirect, incidental, 
                or consequential damages.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Changes to Terms</h2>
              <p className="text-gray-700">
                We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated 
                revision date. Continued use of the service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Contact Information</h2>
              <p className="text-gray-700">
                If you have any questions about these Terms of Service, please contact us at{' '}
                <a href="mailto:legal@fakerbox.com" className="text-blue-600 hover:underline">
                  legal@fakerbox.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
