export const tools = [
  { name: "JSON Beautifier", emoji: "🧩", path: "/tools/json-beautifier" },
  { name: "XML Beautifier", emoji: "📄", path: "/tools/xml-beautifier" },
  { name: "Fake Name Generator", emoji: "👤", path: "/tools/name" },
  { name: "Fake Address Generator", emoji: "🏠", path: "/tools/address" },
  { name: "Fake Phone Number Generator", emoji: "📞", path: "/tools/phone" },
  { name: "Fake Company Name Generator", emoji: "🏢", path: "/tools/company" },
  { name: "Fake Email Generator", emoji: "🌐", path: "/tools/internet" },
  { name: "Lorem Ipsum Generator", emoji: "📝", path: "/tools/loremIpsum" },
  { name: "Fake Product Data Generator", emoji: "🛍️", path: "/tools/commerce" },
  { name: "Fake Finance & Banking Data Generator", emoji: "💰", path: "/tools/finance" },
  { name: "Fake Date Generator", emoji: "📅", path: "/tools/date" },
  { name: "Fake Vehicle Data Generator", emoji: "🚗", path: "/tools/vehicle" },
  { name: "Fake Word Generator", emoji: "📚", path: "/tools/word" },
  { name: "Fake Music Data Generator", emoji: "🎵", path: "/tools/music" },
  { name: "Fake Flight Data Generator", emoji: "✈️", path: "/tools/flight" },
  { name: "Fake Animal Data Generator", emoji: "🐾", path: "/tools/animal" },
  { name: "Fake Book Data Generator", emoji: "📖", path: "/tools/book" },
  { name: "Fake Recipe Generator", emoji: "🍔", path: "/tools/recipe" },
  { name: "Fake Science Data Generator", emoji: "🔬", path: "/tools/science" },
  { name: "Fake Developer Data Generator", emoji: "💻", path: "/tools/developer" },
  { name: "Fake File Data Generator", emoji: "⚙️", path: "/tools/file" },
  { name: "Fake Git Repository Generator", emoji: "🔧", path: "/tools/git-repository" },
  { name: "Fake Datatype Generator", emoji: "📊", path: "/tools/data-type" },
  { name: "Fake Location Generator", emoji: "📍", path: "/tools/location" },
  { name: "Fake String Generator", emoji: "🎲", path: "/tools/string" },
  { name: "Fake Text String Generator", emoji: "🔤", path: "/tools/text-and-char-string" },
  { name: "Fake Image URL Generator", emoji: "🖼️", path: "/tools/image" },
  { name: "Fake Database Generator", emoji: "🗄️", path: "/tools/database" },
  { name: "Fake Array & Object Data Generator", emoji: "🛠️", path: "/tools/helpers" },
];
